# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-local.yml if you use the "local" profile.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} traceId:%X{x-trace-id} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  application:
    name: CRM-ERP
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active:   #spring.profiles.active#

  datasource:
    initialization-mode: always
    #driverclassname: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/milk_store?createDatabaseIfNotExist=true&&relaxAutoCommit=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: postgres
    driverclassname: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3308/in-out #?createDatabaseIfNotExist=true&&relaxAutoCommit=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Rohit123@
    #url: jdbc:mysql://in-out-instance.coopipqh8oi0.ap-south-1.rds.amazonaws.com:3306/in-out #?createDatabaseIfNotExist=true&&relaxAutoCommit=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: admin
    #password: Rohit123
    hikari:
      poolName: JPAHikariCP
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    slow-sql: true
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
  jackson:
    default-property-inclusion: non_null
server:
  port: 4000
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

